site_name: isoplex
site_url: https://fairliereese.github.io/isoplex/
theme:
  name: material
  palette:
    primary: '#fb8072'
    accent: 'orange'
  font:
    text: Montserrat
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Input data formatting: input_data.md
  - API: api.md
  - Contributing: contributing.md
plugins:
  - search
  - mkdocstrings

extra_css:
  - styles/extra.css    # <── path is relative to the docs/ folder

markdown_extensions:
  - admonition
  - pymdownx.highlight          # <-- recommended
  - pymdownx.inlinehilite
  - pymdownx.superfences        # <-- allows fenced code blocks with highlighting
  - codehilite
