name: Deploy Docs

on:
  push:
    branches:
      - main  # or 'master', wherever you want to trigger the build

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repo
      - uses: actions/checkout@v3

      # 2. Set up Python
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # 3. Install dependencies
      - run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocstrings pymdown-extensions

      # 4. Build the site
      - run: mkdocs build --verbose

      # 5. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
